// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihTAaKZ9x2g5JOmttYxy3xVbPTlWNPJ4',
    appId: '1:667675123770:web:fafdb46990e07463cbd503',
    messagingSenderId: '667675123770',
    projectId: 'trial-1-30d06',
    authDomain: 'trial-1-30d06.firebaseapp.com',
    storageBucket: 'trial-1-30d06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCljTDXr0Efx-Bk_uD8wdRFTnIW7WF3r9Y',
    appId: '1:667675123770:android:12660c146c66c31ecbd503',
    messagingSenderId: '667675123770',
    projectId: 'trial-1-30d06',
    storageBucket: 'trial-1-30d06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-jnW71Hx6i7VG7W4tT8wsRDPvbpOpbA',
    appId: '1:667675123770:ios:d4c14e81e465ce7acbd503',
    messagingSenderId: '667675123770',
    projectId: 'trial-1-30d06',
    storageBucket: 'trial-1-30d06.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj-jnW71Hx6i7VG7W4tT8wsRDPvbpOpbA',
    appId: '1:667675123770:ios:d4c14e81e465ce7acbd503',
    messagingSenderId: '667675123770',
    projectId: 'trial-1-30d06',
    storageBucket: 'trial-1-30d06.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAihTAaKZ9x2g5JOmttYxy3xVbPTlWNPJ4',
    appId: '1:667675123770:web:b151d3bc053f442acbd503',
    messagingSenderId: '667675123770',
    projectId: 'trial-1-30d06',
    authDomain: 'trial-1-30d06.firebaseapp.com',
    storageBucket: 'trial-1-30d06.firebasestorage.app',
  );
}
